######################################################################
# Automatically generated by qmake (2.01a) Tue Oct 6 19:48:14 2009
# but modified by me to accomodate for the includes for qwt, hamlib and
# portaudio
######################################################################

TEMPLATE	= app
TARGET		= sdrplayServer
QT		+= widgets network
#CONFIG         += console
CONFIG          -= console
QMAKE_CXXFLAGS  += -std=c++20

QMAKE_CFLAGS    +=  -O3 -ffast-math
QMAKE_CXXFLAGS  +=  -O3 -ffast-math
QMAKE_CXXFLAGS += -isystem $$[QT_INSTALL_HEADERS]
RC_ICONS        =  viewer.ico
RESOURCES       += resources.qrc

TRANSLATIONS = i18n/de_DE.ts i18n/it_IT.ts i18n/hu_HU.ts

DEPENDPATH += . \
	      support \
	      devices \
	      devices/sdrplay-handler-v3
	      

INCLUDEPATH += . \ 
	      support \
	      devices \
	      devices/sdrplay-handler-v3 \
	      devices/sdrplay-handler-v3/include

# Input
HEADERS += ./server.h \
	   ./tcpHandler.h \
	   ./support/ringbuffer.h \
	   ./support/settings-handler.h \
	   ./support/errorlog.h \
	   ./support/spectrum-scope.h \
	   ./support/fft.h \
	   ./support/base-converter.h \
	   ./support/interpolator.h \
	   ./devices/device-exceptions.h \
	   ./devices/device-handler.h \
	   ./devices/sdrplay-handler-v3/sdrplay-handler-v3.h \
	   ./devices/sdrplay-handler-v3/sdrplay-commands.h \
	   ./devices/sdrplay-handler-v3/Rsp-device.h \
	   ./devices/sdrplay-handler-v3/Rsp1A-handler.h \
	   ./devices/sdrplay-handler-v3/RspI-handler.h \
	   ./devices/sdrplay-handler-v3/RspII-handler.h \
	   ./devices/sdrplay-handler-v3/RspDx-handler.h \
	   ./devices/sdrplay-handler-v3/RspDuo-handler.h \
	   ./devices/sdrplay-handler-v3/sdrplayselect-v3.h
	   

FORMS	+= ./server.ui \
	   ./devices/sdrplay-handler-v3/sdrplay-widget-v3.ui

SOURCES += ./main.cpp \
           ./server.cpp \
	   ./tcpHandler.cpp \
	   ./support/settings-handler.cpp \
	   ./support/errorlog.cpp \
	   ./support/spectrum-scope.cpp \
	   ./support/fft.cpp \
	   ./support/base-converter.cpp \
	   ./support/interpolator.cpp \
	   ./devices/device-handler.cpp \
	   ./devices/sdrplay-handler-v3/sdrplay-handler-v3.cpp \
	   ./devices/sdrplay-handler-v3/Rsp-device.cpp \
	   ./devices/sdrplay-handler-v3/Rsp1A-handler.cpp \
	   ./devices/sdrplay-handler-v3/RspI-handler.cpp \
	   ./devices/sdrplay-handler-v3/RspII-handler.cpp \
	   ./devices/sdrplay-handler-v3/RspDx-handler.cpp \
	   ./devices/sdrplay-handler-v3/RspDuo-handler.cpp \ 
	   ./devices/sdrplay-handler-v3/sdrplayselect-v3.cpp

#for Fedora and Ubuntu use
unix { 
DESTDIR		= ./linux-bin

LIBS		+= -lfftw3f
CONFIG          += link_pkgconfig
PKGCONFIG       += libusb-1.0
!mac {
LIBS            += -ldl
}

INCLUDEPATH     += /usr/include/qt6/
INCLUDEPATH     += /usr/include/qt6/qwt
INCLUDEPATH     += /usr/local/include
#correct this for the correct path to the qwt6 library on your system
LIBS           += -lqwt-qt6
}

#
#	the devices
dabstick {
	DEFINES		+= HAVE_RTLSDR
	INCLUDEPATH	+= ./devices/rtlsdr-handler
	HEADERS		+= ./devices/rtlsdr-handler/rtlsdr-handler.h \
	                   ./devices/rtlsdr-handler/dongleselect.h
	SOURCES		+= ./devices/rtlsdr-handler/rtlsdr-handler.cpp \
	                   ./devices/rtlsdr-handler/dongleselect.cpp
	FORMS		+= ./devices/rtlsdr-handler/dabstick-widget.ui
}
#
#	the SDRplay
#
sdrplay {
DEFINES		+= HAVE_SDRPLAY
	INCLUDEPATH	+= ./devices/sdrplay-handler
	HEADERS		+= ./devices/sdrplay-handler/sdrplay-handler.h \
	                   ./devices/sdrplay-handler/sdrplayselect.h
	SOURCES		+= ./devices/sdrplay-handler/sdrplay-handler.cpp \
	                   ./devices/sdrplay-handler/sdrplayselect.cpp
	FORMS		+= ./devices/sdrplay-handler/sdrplay-widget.ui
}

sdrplay-v3 {
DEFINES		+= HAVE_SDRPLAY_V3
	INCLUDEPATH	+= ./devices/sdrplay-handler-v3
	HEADERS		+= ./devices/sdrplay-handler-v3/sdrplay-handler-v3.h \
	                   ./devices/sdrplay-handler-v3/sdrplay-commands.h
	SOURCES		+= ./devices/sdrplay-handler-v3/sdrplay-handler-v3.cpp 
	FORMS		+= ./devices/sdrplay-handler-v3/sdrplay-widget-v3.ui
}

pluto   {
        DEFINES         += HAVE_PLUTO
        QT              += network
        INCLUDEPATH     += ./devices/pluto-handler
        HEADERS         += ./devices/pluto-handler/pluto-handler.h
        SOURCES         += ./devices/pluto-handler/pluto-handler.cpp
        FORMS           += ./devices/pluto-handler/pluto-widget.ui
        LIBS            += -liio -lad9361
}

#
airspy {
	DEFINES		+= HAVE_AIRSPY
	INCLUDEPATH	+= ./devices/airspy-handler \
	                   ./devices/airspy-handler/libairspy
	HEADERS		+= ./devices/airspy-handler/airspy-handler.h 
	SOURCES		+= ./devices/airspy-handler/airspy-handler.cpp 
	FORMS		+= ./devices/airspy-handler/airspy-widget.ui
}
#
#	extio dependencies, windows only
#
extio {
	DEFINES		+= HAVE_EXTIO
	INCLUDEPATH	+= ./devices/extio-handler
	HEADERS		+= ./devices/extio-handler/extio-handler.h \
	                   ./devices/extio-handler/common-readers.h \
	                   ./devices/extio-handler/virtual-reader.h \
	                   ./devices/extio-handler/card-reader.h
	SOURCES		+= ./devices/extio-handler/extio-handler.cpp \
	                   ./devices/extio-handler/common-readers.cpp \
	                   ./devices/extio-handler/virtual-reader.cpp \
	                   ./devices/extio-handler/card-reader.cpp
	FORMS		+= ./devices/extio-handler/extio-widget.ui
}

rtl_tcp {
	DEFINES		+= HAVE_RTL_TCP
	QT		+= network
	INCLUDEPATH	+= ./devices/rtl_tcp
	HEADERS		+= ./devices/rtl_tcp/rtl_tcp_client.h
	SOURCES		+= ./devices/rtl_tcp/rtl_tcp_client.cpp
	FORMS		+= ./devices/rtl_tcp/rtl_tcp-widget.ui
}

elad-s1 {
	DEFINES		+= HAVE_ELAD_S1
	INCLUDEPATH	+= ./devices/sw-elad-s1
	HEADERS		+= ./devices/sw-elad-s1/elad-s1.h \
	                   ./devices/sw-elad-s1/elad-worker.h \
	                   ./devices/sw-elad-s1/elad-loader.h
	SOURCES		+= ./devices/sw-elad-s1/elad-s1.cpp \
	                   ./devices/sw-elad-s1/elad-worker.cpp \
	                   ./devices/sw-elad-s1/elad-loader.cpp
	FORMS		+= ./devices/sw-elad-s1/elad-widget.ui
}

soundcard {
	DEFINES		+= HAVE_SOUNDCARD
	INCLUDEPATH	+= ./devices/soundcard
	HEADERS		+= ./devices/soundcard/pa-reader.h \
	                   ./devices/soundcard/soundcard.h
	SOURCES		+= ./devices/soundcard/pa-reader.cpp \
	                   ./devices/soundcard/soundcard.cpp
	FORMS		+= ./devices/soundcard/soundcard-widget.ui
	LIBS		+= -lportaudio
}

#
#       the HACKRF One
#
hackrf {
        DEFINES         += HAVE_HACKRF
        DEPENDPATH      += ./devices/hackrf-handler
        INCLUDEPATH     += ./devices/hackrf-handler
        HEADERS         += ./devices/hackrf-handler/hackrf-handler.h
        SOURCES         += ./devices/hackrf-handler/hackrf-handler.cpp
        FORMS           += ./devices/hackrf-handler/hackrf-widget.ui
}

#
#       the HACKRF One
#
lime {
        DEFINES         += HAVE_LIME
        DEPENDPATH      += ./devices/lime-handler
        INCLUDEPATH     += ./devices/lime-handler
        HEADERS         += ./devices/lime-handler/lime-handler.h \
       	                   ./devices/lime-handler/lime-reader.h
        SOURCES         += ./devices/lime-handler/lime-handler.cpp \
	                   ./devices/lime-handler/lime-reader.cpp
        FORMS           += ./devices/lime-handler/lime-widget.ui
}

colibri	{
	DEFINES		+= HAVE_COLIBRI
        DEPENDPATH      += ./devices/colibri-handler
        INCLUDEPATH     += ./devices/colibri-handler
        HEADERS         += ./devices/colibri-handler/colibri-handler.h 
        SOURCES         += ./devices/colibri-handler/colibri-handler.cpp 
        FORMS           += ./devices/colibri-handler/colibri-widget.ui
}
